### ISSUE TITLE
Great work! When can we see the code of the research?

### ISSUE THREAD

**Issue by codingchild2424** [invictus717/MetaTransformer#1]
Same as title.

**Comment by invictus717** [comment]
Thank you for your interest in our research! We're currently in the process of cleaning up the code and adding sufficient documentation to make it user-friendly. We understand the importance of making our research reproducible and we're working hard to get the code ready for public release.

We expect to gradually release the code and update the repository in several months.  In addition, this repository will be continually maintained.

Thanks again for your interest and patience!

Best,
Yiyuan
