### ISSUE TITLE
What's the difference between the patch 14 and patch 16 models?

### ISSUE THREAD

**Issue by DemingCheng** [invictus717/MetaTransformer#11]
Hi,
Thanks for your great job!
I'm a beginner in LLM, could you please tell me the difference between the patch 14 and patch 16 models? 
Besides, how to use the pre-trained models? For example, if I want to do a text generation task, should I find a model like llama or vacuna and replace their encoder with this pre-trained encoder models?

**Comment by invictus717** [comment]
I appreciate your interest in Meta-Transformer! The difference between the patch 14 and patch 16 models is only for our image pertaining, which the former one has a larger scale (300M v.s. 80M). The pre-trained model mainly focuses on the encoder part of the whole network. I think your plan is reasonable and it's worth trying. If you have any questions, please let me know.
