### ISSUE TITLE
How can we get the inference demo?

### ISSUE THREAD

**Issue by Jianqiuer** [invictus717/MetaTransformer#13]
How can we get the inference demo? The patch embedding part seems not to be available.

**Comment by invictus717** [comment]
We're committed to creating a user-friendly multimodal processor, simplifying complex tasks through intuitive design and seamless functionality.

**Comment by linhan0109** [comment]
The demo for pretrained encoder just give how to load the model, not show how to use it, so can u give a more  detailed demo a including how to encode certain instance, thanks a lot.

**Comment by invictus717** [comment]
We are working on this, please stay tuned.
