### ISSUE TITLE
what is the difference between vit adapter and MetaTransformer on detection and segmentation task?

### ISSUE THREAD

**Issue by BubblyYi** [invictus717/MetaTransformer#14]
Hi,

Thanks for your greate job.
I'm curious about the difference between the vit adapter and MetaTransformer on detection and segmentation tasks.

Best,
James

**Comment by invictus717** [comment]
We utilize ViT-Adapter as a tool for improving performance on image detection and segmentation tasks. The difference is only about settings on hyper-parameters. You can also perform detection and segmentation tasks without the adapter.
