### ISSUE TITLE
How to use Meta Transformer to finish object detection without ViT-Adapter model?

### ISSUE THREAD

**Issue by shengyuwoo** [invictus717/MetaTransformer#17]
How can I realize the object detection function of an image through MetaTransformer without using the ViT-Adapter model? I don't see the tutorial in your project, is it convenient to remind me?

**Comment by shengyuwoo** [comment]
your job is very nice.  wait for reply.

**Comment by invictus717** [comment]
Thank you for your interest in Meta-Transformer. If you want to directly perform object detection tasks without ViT-Adapter, I think that it's the most convenient approach for implementation is to simply replace the `pretrained_path` in the `MMDetection` library. For example, you can define that `pretrained = 'pretrained/Image_Meta-Transformer_B16.pth''`  in this [config file](https://github.com/open-mmlab/mmdetection/blob/main/configs/timm_example/retinanet_timm-efficientnet-b1_fpn_1x_coco.py). And modify `model_name='vit_base_patch16_224'`, then you can utilize plain Meta-Transformer as common backbone with `MMDetection` library. 

Besides, there is a reminder that `MMDetection` library defines different state keys as the `timm` library, which is mainly utilized in Meta-Transformer. Therefore, please consider transforming the pretrained weights with [this script](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/model_converters/vit2mmseg.py) in `MMSegmentation` library. If you still have some questions, please let me know.

**Comment by shengyuwoo** [comment]
I found that there were too many changes, resulting in mismatches in some related code files and more errors.
Now, I want to run the image object detection function directly in the Meta-Transformer project, can you tell me which models I need to download and where the model path needs to be modified? Also How to start a demo of image object detection?

**Comment by shengyuwoo** [comment]
It's so hard for me to keep going.

**Comment by invictus717** [comment]
> I found that there were too many changes, resulting in mismatches in some related code files and more errors. Now, I want to run the image object detection function directly in the Meta-Transformer project, can you tell me which models I need to download and where the model path needs to be modified? Also How to start a demo of image object detection?

The difference is that you need to resize the position embedding according to the input image size. You can refer to the [implementation](https://github.com/invictus717/MetaTransformer/blob/master/Image/detection/mmdet_custom/models/backbones/base/vit.py) in our repository, which can smoothly solve this with `resize_pos_embed` function.
