### ISSUE TITLE
There is a typo in README file, LOL

### ISSUE THREAD

**Issue by sawyerbutton** [invictus717/MetaTransformer#2]
**After obtaining the token sequence, we employ a modality-shared encoder to extract representation across different modalities. With task-specific heads, Meta-Transformer can hanle various tasks on the different modalities, such as: classification, detection, and segmentation.**

The `hanle` should be `handle`.

LOL, Nice work, forks, and thanks for sharing.

Looking forward to the code.

**Comment by invictus717** [comment]
Thank you for your feedback and catching the typo, it should indeed be 'handle'. We're glad you appreciate our work. The code will be made available on our GitHub repository soon. We're documenting it thoroughly to ensure ease of use. Stay tuned for updates. Thank you for your support and interest.

Best,
Yiyuan
