### ISSUE TITLE
Data2Seq Weights

### ISSUE THREAD

**Issue by johnsutor** [invictus717/MetaTransformer#22]
In the Data2Seq code for getting embeddings, the Image and Video embedders have a Conv2d and Conv3d, respectively. Do you plan to release the pre-trained weights for these layers?

**Comment by invictus717** [comment]
Thank you for expressing interest in our research paper. We are considering the release of pre-trained weights for our embedding layers soon. In the meantime, you can easily leverage modality-specific pre-trained embedding layers for immediate application. Our tests have shown that the Meta-Transformer performs exceptionally well when integrated with MAE and VideoMAE pre-trained modality-specific embedding layers, particularly on the ImageNet and Kinetics-400 datasets.

Should you have any further questions, please feel free to reach out. I'm happy to assist you.
