### ISSUE TITLE
 Enhance Codebase with Comprehensive Docstrings

### ISSUE THREAD

**Issue by rajveer43** [invictus717/MetaTransformer#23]
adding detailed docstrings throughout the code.

- Each function, class, and module in the codebase is accompanied by a comprehensive docstring.
- Docstrings follow the established documentation format and conventions.
- README is updated to include guidelines for writing effective docstrings.

**Comment by invictus717** [comment]
Thank you for your constructive suggestion! We will improve the codebase in line with your recommendations.
