### ISSUE TITLE
what if it not use the LAION-2B dataset CLIP backbone

### ISSUE THREAD

**Issue by Dongshengjiang** [invictus717/MetaTransformer#24]
I wonder the power is or not come from the CLIP backbone that is freezed in your experiments.

**Comment by invictus717** [comment]
Thank you for your insightful question! I'm willing to answer this question as follows:

* Is it necessary to pre-train on LAION-2B?

The answer is no. We have found that simple audio pretraining can also make the network agnostic to some modalities.

* Can CLIP backbone work on various modalities?

We are not sure. Maybe these backbones are also compatible with the Meta-Transformer framework.
