### ISSUE TITLE
demo use

### ISSUE THREAD

**Issue by Zhudogsi** [invictus717/MetaTransformer#26]
After reading your paper, I still don't know how to use your model. Could you please provide a complete example? Please include a full 'Demo of Use for Pretrained Encoder' here. Thank you very much.

**Comment by invictus717** [comment]
Thank you for your interest and constructive suggestions. We will work on a demo for easy use and release it soon.

In addition, could you please tell me which modality you need to deal with, thus I can provide a prompt demo code for your convenience?

**Comment by Zhudogsi** [comment]
Thank you very much for your reply.&nbsp; Text, voice, and image can all be used.


Thank you very much for your reply. Text, voice, and image can all be used.

全都开心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "invictus717/MetaTransformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月29日(星期二) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [invictus717/MetaTransformer] demo use (Issue #26)





 
Thank you for your interest and constructive suggestions. We will work on a demo for easy use and release it soon.
 
In addition, could you please tell me which modality you need to deal with, thus I can provide a prompt demo code for your convenience?
