### ISSUE TITLE
audio模块代码报错

### ISSUE THREAD

**Issue by wuyikai123123** [invictus717/MetaTransformer#27]
Audio模块中的run_sc.sh代码15行，报错提示venvast文件不存在，请问怎么解决？

**Comment by invictus717** [comment]
同学你好，感谢你的问题，第15行在环境配好以后可以直接注释掉，我这就把这个bug改掉，感谢反馈~

**Comment by wuyikai123123** [comment]
您的反馈速度非常快，非常感谢您，祝您科研工作顺利！
