### ISSUE TITLE
Whether to support BBOX data？

### ISSUE THREAD

**Issue by nanfengguli** [invictus717/MetaTransformer#29]
Can you tell me if BBOX data (either 2D or 3D) is currently supported? If not, can you give some guidance on using richer input data types?

**Comment by invictus717** [comment]
Thank you for your interest in Meta-Transformer. However, so far, I never tried to utilize the Meta-Transformer to perceive bonding boxes neither 2D boxes nor 3D boxes. Could you please describe more about "richer input data types" in this question?

**Comment by nanfengguli** [comment]
The "richer input data types" are data types other than the 12 shown on the TEASER, such as bbox, human viewpoint, and so on.
