### ISSUE TITLE
The tokenizer for time-series data

### ISSUE THREAD

**Issue by Arthur-Null** [invictus717/MetaTransformer#3]
The paper mentioned that metaTransformer uses the tokenizer of autoformer for time-series forecasting task. However, autoformer does not have a "tokenizer", and its encoder directly takes the raw time-series data as input. I wonder if you mistake it for PatchTST or something else?

**Comment by invictus717** [comment]
Thanks for your question. We employ a straightforward tokenization approach. The code for time-series forecasting will be cleaned and released tonight (maybe 3-4 hours later). Please keep an eye on our updates.

**Comment by invictus717** [comment]
@Arthur-Null The implementation of MetaTransformer for time-series forecasting tasks has been released. You can also refer to [training logs](https://drive.google.com/file/d/16Qad-t_C4s1zqeIPTtskO71bHCl2uyZ-/view?usp=drive_link). If you have any questions, please let me know.
