### ISSUE TITLE
how to export to Onnx model for faster inference

### ISSUE THREAD

**Issue by eisneim** [invictus717/MetaTransformer#30]
this is a very useful project, would be great if it can be used in production with onnx support

**Comment by invictus717** [comment]
Thank you very much for your constructive suggestions! Could you please specify which part we need to provide onnx support first? Should it be the inference part of our multimodal encoder?

**Comment by eisneim** [comment]
Thank you! 👍 
shared encoder for Text, Image, Audio, Video is the most useful one, those embedings can be used for LLM app that does audio, video retrieval;
searching task would be: image to audio search, image to video clip search, text to audio search, etc.
