### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Meta-Transformer_base_patch16_encoder.pth'

### ISSUE THREAD

**Issue by Eachen11** [invictus717/MetaTransformer#31]
请问Audio目录里面执行sh脚本报错，Meta-Transformer_base_patch16_encoder.pth在哪里呢，没有看到torch.save这个，然后torch.load就报错了

**Comment by invictus717** [comment]
同学你好，感谢你对项目的关注，Meta-Transformer_base_patch16_encoder.pth这个文件在项目的reademe里面提供了下载链接，请先下载到本地修改对应的路径：

谷歌云盘下载链接： https://drive.google.com/file/d/19ahcN2QKknkir_bayhTW5rucuAiX0OXq/view?usp=sharing
国内OpenXLab下载链接：https://download.openxlab.org.cn/models/zhangyiyuan/MetaTransformer/weight//Meta-Transformer_base_patch16_encoder

**Comment by pipiing** [comment]
请问一下已经下载好拉对应的模型，而且放在匹配位置拉，但还是识别不到文件
![image](https://github.com/invictus717/MetaTransformer/assets/95178517/820f814a-2d5e-4e2f-9527-4caaf6975a74)

**Comment by pipiing** [comment]
![image](https://github.com/invictus717/MetaTransformer/assets/95178517/641164cf-aa17-48a9-9926-191d54dda220)
执行run_sc.sh 任务被杀死 请问是什么原因呢 因为没有报错 不太清楚
