### ISSUE TITLE
Is the model that each task will have a corresponding downstream HEAD MLP?

### ISSUE THREAD

**Issue by moonriver0922** [invictus717/MetaTransformer#32]
Great work, thanks.
I have a question that Is the model that each task will have a corresponding downstream HEAD MLP?

**Comment by invictus717** [comment]
Thank you very much for your acknowledgment! For downstream tasks, Meta-Transformer requires relevant task-specific heads to adapt output formats. For example, it requires convolutional layers as the HEAD for image segmentation tasks and MLP layers for classification and other forecasting tasks.

**Comment by moonriver0922** [comment]
Got it. Thanks!
