### ISSUE TITLE
audio问题

### ISSUE THREAD

**Issue by wuyikai123123** [invictus717/MetaTransformer#33]
请问audio部分按教程运行
! bash run_sc.sh
之后为什么会出现log.txt训练记录为空的情况
![屏幕截图 2023-09-07 140227](https://github.com/invictus717/MetaTransformer/assets/98735671/6bf875ed-4c5e-4274-8d4f-111f0af47b17)
![屏幕截图 2023-09-07 140113](https://github.com/invictus717/MetaTransformer/assets/98735671/746aa42c-e02d-4135-9412-04f987d9d90f)

**Comment by shhuangcoder** [comment]
> 请问audio部分按教程运行
> ! bash run_sc.sh
> 之后为什么会出现log.txt训练记录为空的情况
> ![屏幕截图 2023-09-07 140227](https://user-images.githubusercontent.com/98735671/266218789-6bf875ed-4c5e-4274-8d4f-111f0af47b17.png)
> ![屏幕截图 2023-09-07 140113](https://user-images.githubusercontent.com/98735671/266218805-746aa42c-e02d-4135-9412-04f987d9d90f.png)

哈咯，教程在哪里？

**Comment by invictus717** [comment]
同学你好，如果需要记录全部的训练日志的话，我的建议是可以用`nohup`把来执行相应的命令，然后将相应的输出规范到你需要查看的文件就可以了~

**Comment by wuyikai123123** [comment]
感谢

**Comment by KORIYN** [comment]
> 感谢

同学你好，请问这个问题最后是怎么解决的呢？方便回答一下吗
