### ISSUE TITLE
How to pretrain Unified Multimodal Model?

### ISSUE THREAD

**Issue by bbbdbbb** [invictus717/MetaTransformer#35]
I would like to express my appreciation for your exceptional work. I attended your live presentation yesterday and gained valuable insights. I am interested in exploring the Unified Multimodal Model that you proposed within my research domain. As my multimodal data is of fine granularity, I am considering fine-tuning or retraining your model to suit my needs.

I kindly request if it would be possible for you to open-source some of the pretraining procedures for the Unified Multimodal Model. This would greatly assist me in adapting the model to my specific requirements.

Thank you very much for your outstanding contributions.

**Comment by invictus717** [comment]
Thank you for your kindness and interest in Meta-Transformer. Indeed, our implementation is straightforward. For pretraining, you can easily reproduce it with the [openclip](https://github.com/mlfoundations/open_clip) library. If you have any questions, I'm willing to offer my help.
