### ISSUE TITLE
关于text模态的使用

### ISSUE THREAD

**Issue by 1223haohao** [invictus717/MetaTransformer#47]
非常感谢您做了如此出色地工作，给了我非常大的启发!
在利用meta-transformer处理文本模态时，我有这样几个问题有点困惑：
1. 在paper中，对于text的tokenizer，先使用clip将其分割为一系列子词，再用一个embedding层将其向量化。这个embedding层我该如何以代码的方式体现呢？
2. data2seq模块中，是直接使用clip对得到的子词进行了embedding，但这与文章中描述的tokenization的过程有点出入，在这个过程中我们应该只是用一个很轻量级的投影层而非clip吧？
3. 最后，您是否能够提供一个简易的文本模态tokenization的小demo。
感谢再次您如此富有创造力的工作！

**Comment by invictus717** [comment]
很感谢你对我们工作的兴趣，这几个问题分别回答如下：

1. 在paper中，对于text的tokenizer，先使用clip将其分割为一系列子词，再用一个embedding层将其向量化。这个embedding层我该如何以代码的方式体现呢？

其实就是data2seq里面的写法，调用CLIP的文本tokenizer就好了。

2. data2seq模块中，是直接使用clip对得到的子词进行了embedding，但这与文章中描述的tokenization的过程有点出入，在这个过程中我们应该只是用一个很轻量级的投影层而非clip吧？

只有tokenizer，不用它编码器的部分。

3. 最后，您是否能够提供一个简易的文本模态tokenization的小demo。

我找个时间弄一下吧，弄好了在这个issue下面回复你。
