### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by wuyikai123123** [invictus717/MetaTransformer#48]
您好，请问可以提供下
![image](https://github.com/invictus717/MetaTransformer/assets/98735671/8f5725f0-866d-416a-b0ab-5ad313f0eb14)
中针对k400数据集的data preparation的代码吗

**Comment by invictus717** [comment]
https://mmaction2.readthedocs.io/en/latest/user_guides/prepare_dataset.html

**Comment by wuyikai123123** [comment]
感谢您
