### ISSUE TITLE
video

### ISSUE THREAD

**Issue by wuyikai123123** [invictus717/MetaTransformer#50]
您好！我在运行video的run.sh中遇到了如下的问题：
![82E0EC63745B1379058FBC680703B9C7](https://github.com/invictus717/MetaTransformer/assets/98735671/696e617e-3b57-4b1a-8455-7138c7f69d3d)
代码在执行
ckpt = torch.load("Meta-Transformer_base_patch16_encoder.pth")
model.blocks.load_state_dict(ckpt,strict=True)
时遇到了如上报错。
我猜测是由于模型结构不一致造成的，想请教下您是如何解决的，感谢！

**Comment by invictus717** [comment]
Video MAE里面`timm`库的版本是0.4.12那个版本的代码实现qkv还没有被合并，这里可以直接升级到0.9.7

**Comment by wuyikai123123** [comment]
谢谢您

**Comment by wuyikai123123** [comment]
您好，我试了一下升级timm到0.9.7，还是报了相同的错，请问您的torch是什么版本的

**Comment by invictus717** [comment]
1.8.1+cu113

**Comment by begin00001** [comment]
您好，我在运行bash scripts/long_term_forecast/Traffic_script/MetaTransformer.sh出现如下错误：
![image](https://github.com/user-attachments/assets/3e0b6e4f-653b-4ebd-b151-54945c289545)
 ckpt = torch.load("Meta-Transformer_base_patch16_encoder.pth")
FileNotFoundError: [Errno 2] No such file or directory: 'Meta-Transformer_base_patch16_encoder.pth'

请问这个模型是运行哪步生成的？
