### ISSUE TITLE
Questions about experiments

### ISSUE THREAD

**Issue by yangbang18** [invictus717/MetaTransformer#51]
Hi, thanks for your great contributions. 

I have some questions after reading your paper:

1. In Table 3 (GLUE benchmark), you present `Size` for pre-training but do not give the corresponding `unit`. I know that LAION-2B contains `2B` image-text pairs. But what do `0.8B`, `3.3B`, `4,5000B` mean for language models? The number of tokens or the disk space of text files?
2. In Table 3 (GLUE benchmark), the model with frozen LAION-2B-pretrained backbone (i.e., `Meta-Transformer-B16_F`) lags behind the SOTA performance by a large margin (similarly in Table 9 - video understanding, and Table 12 - graph data understanding). In terms of this, I mentioned in [issue#49](https://github.com/invictus717/MetaTransformer/issues/49) that `the released Meta-Transformer weights may give inferior representations`, especially for modalities like text, video and graph (because the backbone is pre-trained on LAION-2B, not trained jointly on data across 12 modalities). Do I misunderstand or overlook sth? It seems that one would have to fine-tune the backbone to get more discriminative representations (e.g., Table 3, `Meta-Transformer-B16_F` vs. `Meta-Transformer-B16_T`).

**Comment by invictus717** [comment]
1. Yes, 0.8B, 3.3B, and 4,5000B are pretraining tokens for these language models.
2. It's insightful of your observations. Yes, Meta-Transformer delivers limited performance in video, graph, and text understanding, even though it's outstanding in point cloud, time-series, audio, and IMU data understanding. It seems that finetuning will bring better performance. But, I think that the key design is how to perform data tokenization. Meanwhile, we found that an easy approach can effectively enhance the performance in time-series forecasting tasks.
