### ISSUE TITLE
为什么训练图像会出现这种错误

### ISSUE THREAD

**Issue by CQU1213** [invictus717/MetaTransformer#53]
我使用的Image中的htc++模型，数据集按照readme.md中的要求下载了COCO数据集，但是在训练过程中老是提示如下错误FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/stuffthingmaps/train2017/000000248242.png'，但是数据集中所有文件都是jpg，改称png后，有一些数据又要用到png。请问我该如何解决这个问题

**Comment by invictus717** [comment]
诶，我没遇到过诶

**Comment by invictus717** [comment]
你用的是mmdetection来下载的数据集吗 目标检测的实验很好复现呀

**Comment by CQU1213** [comment]
https://opendatalab.com/OpenDataLab/COCO_2017使用的是这个数据集吗

**Comment by CQU1213** [comment]
使用的是这个数据集吗
https://opendatalab.com/OpenDataLab/COCO_2017

**Comment by invictus717** [comment]
```bash
data/coco
├── annotations
│     ├── stuff_train2017.json
├── train2017
├── val2017
├── test2017
├── unlabeled2017
├── unlabeled2017

```
请用MMdetection的[相关文档](https://github.com/open-mmlab/mmdetection/blob/main/docs/zh_cn/user_guides/dataset_prepare.md)来下载安装吧.
`python tools/misc/download_dataset.py --dataset-name coco2017`
