### ISSUE TITLE
Data2Seq > Hyper_Spectrum.py update from self.cls_tokens to self.cls_token

### ISSUE THREAD

**Issue by jawhster** [invictus717/MetaTransformer#54]
https://github.com/invictus717/MetaTransformer/blob/d30327826f4c2f158df137568e9557cb715026ec/Data2Seq/Hyper_Spectrum.py#L21C9-L21C69

From
`cls_tokens = repeat(self.cls_tokens, '() n d -> b n d', b=b)`

To
`cls_tokens = repeat(self.cls_token, '() n d -> b n d', b=b)`

Which would be equivalent to https://github.com/invictus717/MetaTransformer/blob/d30327826f4c2f158df137568e9557cb715026ec/Hyper-spectrum/metatransformer.py#L156?

**Comment by invictus717** [comment]
Please use this [code](https://github.com/invictus717/MetaTransformer/blob/d30327826f4c2f158df137568e9557cb715026ec/Hyper-spectrum/metatransformer.py#L156)
