### ISSUE TITLE
请问使用 Data2seq的 tokenizer 时输入数据的格式

### ISSUE THREAD

**Issue by Zoew420** [invictus717/MetaTransformer#55]
在不同数据使用Data2Seq时，请问可以出一个Readme 介绍一下输入规定的格式吗，比如是`dataloader` 还是 `torch.data.dataset` 等。

**Comment by invictus717** [comment]
demo code里面是以某一个instance为例的，具体在您的实验里面，您构建好了`dataloader`以后直接在迭代数据的时候使用代码里的tokenizer；或者您也可以直接将tokenizer部分的代码放入到您的神经网络部分的代码，这样可能更方便使用~
