### ISSUE TITLE
运行环境配置说明

### ISSUE THREAD

**Issue by jinpeifei2015** [invictus717/MetaTransformer#56]
非常感谢您做了如此出色地工作，给了我非常大的启发!
     我后续会持续跟踪您的更新，请问这个工程的如何一步步配置完成的，有对应的说明吗？

感谢再次您如此富有创造力的工作！

**Comment by invictus717** [comment]
您看一下对应您要用的数据模态，进入到对应的文件夹里面有相应的说明文档~
