### ISSUE TITLE
Hardware configurations for fine-tuning?

### ISSUE THREAD

**Issue by tctco** [invictus717/MetaTransformer#58]
Hi! I'm very interested in your research project and wish to fine-tune the meta-transformer on my own dataset (mostly multi-modal medical data). Could you provide a (minimal and recommended) hardware configuration for this purpose?

Thanks!

**Comment by invictus717** [comment]
Thank you for your interest! If you wish to fine-tune our pretrained weights on your own dataset, I think 1 GPU card is enough.
