### ISSUE TITLE
question about training

### ISSUE THREAD

**Issue by LinB203** [invictus717/MetaTransformer#6]
I wonder that could the modality A interact with modality B in training? 
I guess that each tokenizer process their modality sperately, each modality was transformed by the freezed encoder(concat all the data and set the attention mask if modality A can **not** interact with modality B, or just forward 12 times?), and each modality was sent to its head to calculate loss.
Am I right?

**Comment by LinB203** [comment]
> Thank you for your interest in Meta-Transformer. In our paper, we introduce how we conduct multimodal experiments e.g. audio-visual semantic segmentation on Page23 SecC.1. Without any fusion module, Meta-Transformer can outperform existing state-of-the-art methods directly, as experimental results are shown in Table.13. We simply CONCATENATE these visual and audio embeddings after Data2Seq tokenization. We believe that the modality-shared encoder can learn modality-invariant patterns, at the same time, it can also autonomously fuse multimodal features. If you have any question, please let me know.

All modalities share one training with multi-task loss, or 12 trainings, each training has one task loss?

**Comment by LinB203** [comment]
> Thank you for your interest in Meta-Transformer. In our paper, we introduce how we conduct multimodal experiments e.g. audio-visual semantic segmentation on Page23 SecC.1. Without any fusion module, Meta-Transformer can outperform existing state-of-the-art methods directly, as experimental results are shown in Table.13. We simply CONCATENATE these visual and audio embeddings after Data2Seq tokenization. We believe that the modality-shared encoder can learn modality-invariant patterns, at the same time, it can also autonomously fuse multimodal features. If you have any question, please let me know.

What does the attention mask look like during training?

**Comment by invictus717** [comment]
The former did not lead to training divergence. The latter also works. In addition, training with several of the 12 modalities can also benefit from Meta-Transformer. It's up to you to manage your experimental settings.

**Comment by LinB203** [comment]
> The former did not lead to training divergence. The latter also works. In addition, training with several of the 12 modalities can also benefit from Meta-Transformer. It's up to you to manage your experimental settings.

I just wonder that meta-transformer will choose which one? There is a little imformation about training in paper.
