### ISSUE TITLE
Amount of embeddings

### ISSUE THREAD

**Issue by vzapylikhin** [invictus717/MetaTransformer#61]
Hello! We are continuing to study your project. I would like to know when we combine tokens of two modalities, such as text (1 x 768) and pictures (1 x 768), then we get a token using torch.concat (2x768). 

features = torch.concat([text_tokenizer(text), image_tokenizer(image)],dim=1)

Then, after the encoder, we get a 2x768 embedding. But since both the text and the picture belong to the same data line, we would like to get a 1x768 embedding. How to do it?

**Comment by invictus717** [comment]
Following common practice, we propose to `concat` these two embeddings, if your target is to merge or fuse these two embeddings, you can try `plus`, `dot product`, `convolution` operations.
