### ISSUE TITLE
下游任务的代码

### ISSUE THREAD

**Issue by CQU1213** [invictus717/MetaTransformer#62]
现在关于meta transformer的下游任务的代码是否没有发布，只发布了其他模型的下游任务代码。假如我要使用meta transformer完成目标检测该如何完成，能否提供一个demo。感谢。

**Comment by invictus717** [comment]
下游任务的代码已经开源了，可以看一下这个[说明文档](https://github.com/invictus717/MetaTransformer/tree/master/Image/detection)

**Comment by CQU1213** [comment]
你好，我使用多模态进行目标检测，输入数据应该是多模态数据而不仅仅是一张图片吧，为什么在目标检测中image_demo.py的参数中只输入了一张图片进行目标检测呢？

**Comment by CQU1213** [comment]
假如说我现在想使用metatransformer和自己的数据集来训练一个多模态目标检测模型，我应该怎么做呢？
