### ISSUE TITLE
meta-transformer能否进行三维CT或者核磁数据的分割和检测？

### ISSUE THREAD

**Issue by li-pengcheng** [invictus717/MetaTransformer#65]
对于CT图像的语义分割来说，是否可以和高光谱图像分类的pipeline一样处理？

**Comment by invictus717** [comment]
我们之前尝试过一些CT图像的结果，可以试一下Finetune参数在CT图像的语义分割问题中

**Comment by li-pengcheng** [comment]
3D的CT数据在当前代码中的哪个模态finetune呢？
