### ISSUE TITLE
Data2Seq中的Vedio.py有问题

### ISSUE THREAD

**Issue by li-pengcheng** [invictus717/MetaTransformer#66]
PatchEmbed函数的patch_size应该是三个通道吧？
self.proj是3D卷积。
视频的输入shape应该是（B,C,T,H,W）吧？

class PatchEmbed(nn.Module):
    """
    2D Image to Patch Embedding
    """
    def __init__(self, img_size=224, patch_size=16, in_c=3, embed_dim=768, norm_layer=None):
        super().__init__()
        img_size = (img_size, img_size)
       ` patch_size = (patch_size, patch_size)`
        self.img_size = img_size
        self.patch_size = patch_size
        self.grid_size = (img_size[0] // patch_size[0], img_size[1] // patch_size[1])
        self.num_patches = self.grid_size[0] * self.grid_size[1]
        `self.proj = nn.Conv3d(in_c, embed_dim, kernel_size=patch_size, stride=patch_size)`
        self.norm = norm_layer(embed_dim) if norm_layer else nn.Identity()

 def forward(self, x):
       ` B, C, H, W = x.shape`

**Comment by invictus717** [comment]
这里单纯是把2D的Patch Embed改成了3D Patch Embed，将原来处理图像的2D卷积改成了3D即可
