### ISSUE TITLE
About the point cloud model release time?

### ISSUE THREAD

**Issue by Roywangj** [invictus717/MetaTransformer#7]
Hi, thanks for your great work, when will the point cloud model release?

**Comment by invictus717** [comment]
Thank you for your interest in Meta-Transformer. Implementation regarding point cloud consists of two major components. One is normal PointPatchEmbedding, and the other is Multi-view Prompts Emeddbings. We are working on merging these two components to provide higher-quality code for the community. Please stay tuned.

**Comment by Roywangj** [comment]
Thanks for your reply
