### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by bjut-chunxiwang** [invictus717/MetaTransformer#70]
请问在audio中 只支持input_fdim=224,input_dim=224么？如果我的test_input=torch.rand([10,1997,30])  呢？

**Comment by invictus717** [comment]
不是的 应该是任意形状 改一下tokenizer的参数形状就好

**Comment by bjut-chunxiwang** [comment]
ast_mdl = ASTModel(label_dim=527, fstride=10, tstride=10, input_fdim=30, input_tdim=1997, imagenet_pretrain=True, audioset_pretrain=False, model_size='base384', verbose=True)
   
test_input = torch.rand([10, 1997, 30])
test_output = ast_mdl(test_input)

报错：AssertionError: Input height (30) doesn't match model (224).
请问这个model （224）在程序的哪个部分，应该如何修改Audio部分的ast_models
使得模型可以适应我这种维度的输入

**Comment by invictus717** [comment]
这个需要更改的是这里

https://github.com/invictus717/MetaTransformer/blob/b08a2bee6dae578bbbedd124859bfe4201181681/Audio/src/models/ast_models.py#L35

**Comment by invictus717** [comment]
把assert关了或者改成你要的形状就行了 你这里提到的张量的形状和meta-transformer的forward没有关系的
