### ISSUE TITLE
Can Meta-Transformer perform similar information retrieval to ImageBind?

### ISSUE THREAD

**Issue by duguyue100** [invictus717/MetaTransformer#71]
Hi,

Great work! I read the paper and it extends the number of modalities from 6 in ImageBind to 12 without paired data.
I'm wondering with Meta-Transformer if the network can also perform a similar cross-domain information retrieval as in ImageBind.

Particularly, ImageBind can compute similarities between embeddings from different modalities here: https://github.com/facebookresearch/ImageBind#usage

**Comment by invictus717** [comment]
No, it's a universal encoder only. While, you can refer to our new work named [MiCo](https://github.com/invictus717/MiCo), which can perform caption, retrieval (similarity), and QA tasks among most modalities by pretraining text-image-depth-video-audio paired data.

**Comment by duguyue100** [comment]
Thanks for the reply, so the paper's main claim would be that a pre-trained ViT can be a transfer learning backbone for multiple modalities, correct?

**Comment by invictus717** [comment]
It would be transformer blocks only, instead of the whole ViT.
