### ISSUE TITLE
about Modality-Agnostic Models

### ISSUE THREAD

**Issue by regainOWO** [invictus717/MetaTransformer#72]
Hi! Thanks for your great contributions!
I want to know how the `Meta-Transformer-B16` and `Meta-Transformer-L14` model files are trained?. I found its the Transformer Block weights.

**Comment by invictus717** [comment]
They're simple pretrained CLIP models on the LAION-2B dataset, we only use the transformer blocks and use the proposed modality-specific tokenizers in our paper among these modalities.

**Comment by regainOWO** [comment]
Thanks for your reply!
what about `Image_Meta-Transformer-B16`, Is it obtained by training `Meta-Transformer-B16` as ViT on ImageNet-1K dataset?
![image](https://github.com/user-attachments/assets/375829cc-85dd-47f1-b648-7ede54a2659c)

**Comment by invictus717** [comment]
It's a finetuned Meta-Transformer weight on the image datasets.
