### ISSUE TITLE
Finetuning the model

### ISSUE THREAD

**Issue by shahkalp09** [invictus717/MetaTransformer#8]
First of all, great work by your team, this will be the new breakthrough in AI.
How can we Finetune the Meta Transformer model with our task-specific data?

**Comment by invictus717** [comment]
I appreciate your interest in Meta-Transformer. Meta-Transformer provides a general-purpose encoder, which could be utilized for known 12 modalities. We suggest that you can first transform input data into a token sequence then you can replace your original encoder with a Meta-Transformer encoder for custom data.
