### ISSUE TITLE
预训练模型内地如何下载？

### ISSUE THREAD

**Issue by hsiangbinhua** [invictus717/MetaTransformer#9]
[赞]，非常棒的开源项目，可是我们国内没法访问墙外的谷歌，是否有计划将预训练模型国内也上传一份呢？

**Comment by invictus717** [comment]
您好，非常感谢您对MetaTransformer的支持与兴趣！对于开源预训练模型的国内渠道，我会在今天之内将模型上传到Open MMLab的浦源开源平台（Open X Lab），敬请您持续关注，感谢您的问题。

**Comment by invictus717** [comment]
您好，截至目前所有在Google drive上传的模型文件已经在OpenXLab实现了模型托管，可以在https://openxlab.org.cn/models/detail/zhangyiyuan/MetaTransformer 查看下载
